# Generated by Django 3.2.8 on 2021-12-14 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('date_of_birthday', models.DateField()),
                ('sex', models.CharField(max_length=7, verbose_name='Пол')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='Место рождения')),
                ('place_of_life', models.CharField(max_length=100, verbose_name='Адрес проживания')),
                ('education', models.CharField(max_length=100, verbose_name='Образование')),
                ('profession', models.CharField(max_length=50, verbose_name='Занимаемая должность')),
                ('is_doctor', models.BooleanField(default=False)),
                ('id_cards', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.users', verbose_name='Номер карточки')),
            ],
        ),
    ]
